### ISSUE TITLE
playsound() crashes the execution

### ISSUE THREAD

**Issue by Alaneczek123123851** [AlexBerejnov/RobloxAccountGeneratorSelenium#3]
If you play alarm.wav second time then it crashes

**Comment by AlexBerejnov** [comment]
@Alaneczek123123851 Have you installed the **[playsound](https://pypi.org/project/playsound/)** package?

**Comment by Alaneczek123123851** [comment]
> @Alaneczek123123851 Have you installed the **[playsound](https://pypi.org/project/playsound/)** package?

Yes

**Comment by AlexBerejnov** [comment]
What is the error?

**Comment by Alaneczek123123851** [comment]
No error it just crashes

**Comment by AlexBerejnov** [comment]
Consider removing **playsound()** functions from the code. Since there is no error, I can't really help with anythin g
